---
title: "lab 6 DATA 606"
author: "Neil Hodgkinson"
date: "2022-10-16"
output:
  html_document:
    df_print: paged
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(openintro)
library(infer)
```

```{r Exercise 1 & 2}

table (yrbss$text_while_driving_30d)

yrbss %>%filter(text_while_driving_30d =="30" & helmet_12m =="never") %>%nrow()/nrow(yrbss)

```

## E1&2
0= 4792, 1-2 = 925, 6-9 = 311, 10-19 = 373, 20-29 = 298, 30 = 827, DND = 4646

The proportion is 0.034

```{r Exercise 3}
p <-yrbss %>%filter(text_while_driving_30d =="30" & yrbss$helmet_12m =="never") %>%nrow()/nrow(yrbss)

ME<-1.96*sqrt(p*(1-p)/nrow(yrbss))
ME

```
## Exercise 3

ME=0.003


```{r}
table(yrbss$physically_active_7d)
n1 <-yrbss %>%filter( physically_active_7d > 6) %>%nrow(); n1
n = nrow(yrbss); n
p <- n1/n; p
ME<-1.96*sqrt(p*(1-p)/nrow(yrbss))
ME
c(p - ME, p + ME)
table(yrbss$strength_training_7d)
n1 <-yrbss %>%filter( strength_training_7d > 3) %>%nrow(); n1
n = nrow(yrbss); n
p <- n1/n; p
ME<-1.96*sqrt(p*(1-p)/nrow(yrbss))
ME
c(p - ME, p + ME)
```

```{r}
n <- 1000
p <- seq(from = 0, to = 1, by = 0.01)
me <- 2 * sqrt(p * (1 - p)/n)
dd <- data.frame(p = p, me = me)
ggplot(data = dd, aes(x = p, y = me)) + 
  geom_line() +
  labs(x = "Population Proportion", y = "Margin of Error")

n <- 10
p <- seq(from = 0, to = 1, by = 0.01)
me <- 2 * sqrt(p * (1 - p)/n)
dd <- data.frame(p = p, me = me)
ggplot(data = dd, aes(x = p, y = me)) + 
  geom_line() +
  labs(x = "Population Proportion", y = "Margin of Error")
```
## Exercise 5

The ME seems to increase with the population increase. At 50% it begins to decrease

```{r}
n <- 300
p <- seq(from = 0, to = 1, by = 0.01)
me <- 2 * sqrt(p * (1 - p)/n)
dd <- data.frame(p = p, me = me)
ggplot(data = dd, aes(x = p, y = me)) + 
  geom_line() +
  labs(x = "Population Proportion", y = "Margin of Error")
```

## Exercise 6

The shape appears to be mostly normal

```{r}
p<-0.1
n<-300

(p*(1-p)/n)^.5
.1-(p*(1-p)/n)^.5
.1+(p*(1-p)/n)^.5
```


```{r}
p<-0.1
n<-400

(p*(1-p)/n)^.5
.1-(p*(1-p)/n)^.5
.1+(p*(1-p)/n)^.5
```

## Exercise 8

As n increases, p becomes tighter

```{r}
sleep <- yrbss  %>%
  filter(school_night_hours_sleep == "10+")

strengthTraining <- yrbss %>%
  mutate(text_ind = ifelse(strength_training_7d == "7", "yes", "no"))
strengthTraining %>%
  filter(text_ind != "") %>%
  specify(response = text_ind, success = "yes") %>%
  generate(reps = 1000, type = "bootstrap") %>%
  calculate(stat = "prop") %>%
  get_ci(level = 0.95)
```

## Exercise 10

Type 1 is a false positive, so we can reject the null hypothesis.

## Exercise 11

ME= 1.96SE = 1.96 (p(1-p)/n)^0.5

